services:
  # Backend API service
  - type: web
    name: cre-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd cre_platform_backend && pip install -r requirements.txt
    startCommand: cd cre_platform_backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: db_cre
          property: connectionString
      - key: FIREWORKS_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true

databases:
  - name: db_cre
    databaseName: db_cre
    user: db_cre_user
    plan: free
